### ISSUE TITLE
1st phase SampleCloud

### ISSUE THREAD

**Issue by ikisusi** [ouspg/SampleCloud#6]
Static README.md referring to 3rd party fuzzing sample (corpus) source

**Comment by WhiteEyeDoll** [comment]
Template with an example [here](https://github.com/ouspg/SampleCloud/blob/master/doc/EXAMPLE_SAMPLES.md).

GitHub's center column is a tad too narrow for it but [Wide Github](https://chrome.google.com/webstore/detail/wide-github/kaalofacklcidaampbokdplbklpeldpj?hl=en) "fixes" it.
